# Generated by Django 3.1.2 on 2020-12-26 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201226_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
        migrations.CreateModel(
            name='Lk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='network.item')),
            ],
        ),
    ]
